version: '3'
services:

    mysql:
        image: mysql:5.7
        volumes:
            - $PWD/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        privileged: true
        ports:
            - "3306:3306"

    php-fpm:
        build: .
        volumes:
            - $PWD/wxphp:/var/www/html
            - $PWD/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - $PWD/php.ini:/usr/local/etc/php/php.ini
        restart: always
        ports:
            - "9000:9000"
        depends_on:
            - mysql

    nginx:
        image: nginx
        volumes:
            - $PWD/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php-fpm
  
